start_message: "
👋Привет \n\n
 Ты можешь писать мне **любые сообщения — я обязательно** передам их администратору. \n
 Просто изложи свою просьбу или вопрос максимально подробно 🥺 \n\n
 ⚠️ Учти за спам ты можешь попасть в чс бота ⚠️ \n"

send_message_to_admin: "Введите сообщение которое вы хотите отправить администратору."
successful_send: "Сообщение успешно отправлено администратору."
unknown_command: "Я не знаю такой команды =(. \nЕсли хочешь начать сначала напиши **/start**"
blocked_message: "Вы были заблокированы."
not_enough_rights: "Недостаточно прав."